### ISSUE TITLE
Plugin není kompatibilní s novou verzí IDEA 2023.3.x

### ISSUE THREAD

**Issue by JardaHudec** [mikrop/quick-fix#1]
Plugin není kompatibilní s novou verzí IDEA 2023.3.x: 
_"Plugin 'Quick-Fix' (version '1.0-SNAPSHOT') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-233.11799.300"_
Bylo by možné to nparavit? Díky! 😉

**Comment by mikrop** [comment]
Odstraněn attribut until-build version, aby bylo možné používat s novějšími verzemi IDE.

**Comment by mikrop** [comment]
Odstraněn attribut until-build, aby bylo možné používat s novějšími verzemi IDE. Uložena nová verze quick-fix-1.0-SNAPSHOT.zip
